### ISSUE TITLE
[1pt] Setup Kanban Board

### ISSUE THREAD

**Issue by mrjuda** [mrjuda/comt#2]
Setup kanban board from the Microverse template
Link to the project's kanban board:
[https://github.com/mrjuda/comt/projects/1](https://github.com/mrjuda/comt/projects/1)

Members: we are in 3 (three):
[Member 1] >> [@mrjuda](https://github.com/mrjuda)
[Member 2] >> [@NduatiKagiri](https://github.com/NduatiKagiri)
[Member 3] >> [@Bushido-brown](https://github.com/Bushido-brown)

**Comment by t-yanick** [comment]
Hi Team, 

### Good job so far!
### To Highlight! :clap:  :green_circle: 

:heavy_check_mark:  Descriptive issue summary

There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

- [ ] Please kindly update your [link](https://github.com/mrjuda/comt/projects/1) to take your directly to the kanban board and not your repository. 
- [ ] Please kindly make sure all cards are assigned to team members. You should see a circle with user's avatar on each card(see image below). 

![assign](https://user-images.githubusercontent.com/62849872/189761978-712ccf08-b3f2-481c-aedd-79cfef56b6d7.png)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

### N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Lordkaito** [comment]
Hi @mrjuda, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
